####################### 用途 ######################

# 主要负责使用指定的tag创建、推送镜像
# docker的tag通常由git tag指定
# 若在master上则为lastest

###################################################

####################### 说明 ######################

# https://docs.docker.com/ci-cd/github-actions/

# 分支说明
# master ---------- 最新的稳定的代码
# dev ------------- 最新的经过测试的代码
# bugfix-* -------- 用于修复bug的代码
# feature-* ------- 用于开发新功能的代码
# v* -------------- git tag
# others ---------- 不予维护

# 何时触发该工作流
# 向repo推送tag时触发
# 向master合并pull request时触发

###################################################
name: Push Docker Image

on:
  push:
    tags: [ "v*" ]
    branches: [ "t*" ]

  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

  workflow_call:

# 一个工作流的运行是由一个以上的工作按顺序或平行的执行而组成的
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 将你的仓库检出到机器的$GITHUB_WORKSPACE目录中，以便下面继续运行
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get tag to build
        id: tag
        run: |
          ref="${{ github.ref }}"
          tag=`echo ${ref##*/}`
          if [ $tag == "master" ]; then tag="latest"; fi
          echo "current ref: $ref"
          echo "using tag: $tag"
          echo ::set-output name=tag::$tag
        
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/v2ray-ws:${{ steps.tag.outputs.tag }}
      #     cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/v2ray-ws:buildcache
      #     cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/v2ray-ws:buildcache,mode=max
